src/AppBundle/Entity/Foto.php
<?php
namespace AppBundle\Entity;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
/**
 * @ORM\Entity
 * @ORM\Table(name="fotos")
 */
class Foto
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=256)
     * @Assert\NotBlank()
     */
    protected $link_foto;

    /**
    * @ORM\ManyToOne(targetEntity="PuntoInteres", inversedBy="fotos")
    * @Assert\NotBlank()
    */
    protected $puntoInteres;

    public function getId()
    {
        return $this->id;
    }

    public function getLink()
    {
        return $this->link_foto;
    }

    public function setLink($aLinkFoto)
    {
        $this->link_foto = $aLinkFoto;
    }

    public function setPuntoInteres(PuntoInteres $puntoInteres)
    {
        $this->puntoInteres = $puntoInteres;
    }
}

src/AppBundle/Entity/PuntoInteres.php
<?php
namespace AppBundle\Entity;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 * @ORM\Table(name="puntos_interes")
 */
class PuntoInteres
{

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\NotBlank()
     */
    protected $nombre;

    /**
     * @ORM\Column(type="string", length=256)
     * @Assert\NotBlank()
     */
    protected $descripcion;

    /**
     * @ORM\Column(type="string", length=50)
     */
    protected $latitud;

    /**
     * @ORM\Column(type="string", length=50)
     */
    protected $longitud;

    /**
     * @ORM\Column(type="string", length=256)
     * @Assert\Url()
     */
    protected $link_interes;

    /**
     * @ORM\Column(type="string", length=256)
     */
    protected $direccion;

    /**
     * @ORM\ManyToOne(targetEntity="Localidad")
     */
    protected $localidad;   

    /**
     * @ORM\ManyToMany(targetEntity="Categoria", cascade={"persist"})
     */
    protected $categoria;

    /**
     * @ORM\OneToMany(targetEntity="Foto", cascade={"persist"}, mappedBy="puntoInteres")
     */
    protected $fotos;

    /**
     * @ORM\OneToMany(targetEntity="Video", cascade={"persist"}, mappedBy="puntoInteres")
     */
    protected $videos;

    /**
     * @ORM\OneToMany(targetEntity="Precio", cascade={"persist"}, mappedBy="puntoInteres")
     */
    protected $precios;

    public function __contruct()
    {
        $this->categoria = new ArrayCollection();
        $this->fotos = new ArrayCollection();
        $this->videos = new ArrayCollection();
        $this->precio = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getNombre()
    {
        return $this->nombre;
    }

    public function setNombre($aNombre)
    {
        $this->nombre = $aNombre;
    }

    public function getDescripcion()
    {
        return $this->descripcion;
    }

    public function setDescripcion($aDescripcion)
    {
        $this->descripcion = $aDescripcion;
    }

    public function getLatitud()
    {
        return $this->latitud;
    }

    public function setLatitud($aLatitud)
    {
        $this->latitud = $aLatitud;
    }

    public function getLongitud()
    {
        return $this->longitud;
    }

    public function setLongitud($aLongitud)
    {
        $this->longitud = $aLongitud;
    }

    public function getLinkInteres()
    {
        return $this->link_interes;
    }

    public function setLinkInteres($aLinkInteres)
    {
        $this->link_interes = $aLinkInteres;
    }

    public function getDireccion()
    {
        return $this->direccion;
    }

    public function setDireccion($aDireccion)
    {
        $this->direccion = $aDireccion;
    }

    public function getCategoria()
    {
        return $this->categoria;
    }
        
    public function addCategoria($aCategoria)
    {
        $this->categoria[] = ($aCategoria);
        $aCategoria->setPuntoInteres($this);
    }

    public function removeCategoria($aCategoria)
    {
        $this->categoria->remove($aCategoria);
    }

    public function getLocalidad()
    {
        return $this->localidad;
    }

    public function setLocalidad(Localidad $aLocalidad)
    {
        $this->localidad = $aLocalidad;
    }

    public function getFotos()
    {
        return $this->fotos;
    }

    public function setFotos($aFoto)
    {
        $this->fotos = $aFoto;
    }

    public function addFoto(Foto $aFoto)
    {
        $this->fotos[] = $aFoto;
        $aFoto->setPuntoInteres($this);
    }

    public function removeFoto($aFotos)
    {
        $this->fotos->remove($aFotos);
    }

    public function getVideos()
    {
        return $this->videos;
    }

    public function setVideos($aVideo)
    {
        $this->videos = $aVideo;
    }

    public function addVideo(Video $aVideo)
    {
        $this->videos[] = $aVideo;
        $aVideo->setPuntoInteres($this);
    }

    public function removeVideo($aVideos)
    {
        $this->videos->remove($aVideos);
    }

    public function getPrecios()
    {
        return $this->precios;
    }

    public function addPrecio(Precio $aPrecios)
    {
        $this->precios[] = $aPrecios;
        $aPrecios->setPuntoInteres($this);
    }

    public function getImagenPrincipalUrl()
    {
        if ($this->fotos->isEmpty()) {
            return '';
        }
        else {
            return $this->fotos[0]->getLink();
        }
    }
}

src/AppBundle/Controller/PuntosInteresController.php
<?php

namespace AppBundle\Controller;
use AppBundle\Entity\PuntoInteres;
use AppBundle\Entity\Categoria;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;

class PuntosInteresController extends Controller
{
    /**
     * @Route("/puntos-interes", name="puntosinteres_index")
     */
    public function indexAction(Request $request)
    {        
        $punto = new PuntoInteres();
        $categorias = new Categoria();
    
        $qbCategorias = $this->getDoctrine()->getManager()->createQueryBuilder('c');
        $qbCategorias->select('c')
            ->from('AppBundle:Categoria','c');
    
        $categorias = $qbCategorias->getQuery()->getResult();
    
        $form = $this->createFormBuilder()
            ->setMethod('GET')
            ->add('nombre', 'text')
            ->add('Filtrar', 'submit')
    
            ->getForm();
    
        $qb = $this->getDoctrine()->getManager()->createQueryBuilder('p');
        $qb->select('p')
            ->from('AppBundle:PuntoInteres','p');
    
        $form->handleRequest($request);
    
        if($form->isSubmitted() && $form->isValid()) {
    
            $criteria = $form->getData();
            // die(var_dump($criteria['categoria']));
    
            $qb->where( 
                        $qb->expr()->orX(
                            $qb->expr()->like('p.nombre','?1'),
                            $qb->expr()->like('p.descripcion','?1')))
                ->setParameter(1,'%' . $criteria['nombre'] . '%');
                
            $puntosInteres = $qb->getQuery()->getResult();
        }else {
            $puntosInteres = $this->getDoctrine()->getRepository('AppBundle:PuntoInteres')->findAll();
        }
    
        return $this->render(
            'AppBundle:puntosinteres:filtro.html.twig', 
            array('puntosinteres' => $puntosInteres, 'form' => $form->createView(),));
  }

    /**
     * @Route("/puntos-interes/{id}", name="puntosinteres_completo")
     * @Method("GET")
     */
    public function completoAction(PuntoInteres $puntoInteres)
    {
        return $this->render(
            'AppBundle:puntosinteres:articuloCompleto.html.twig', 
            array('puntoInteres' => $puntoInteres,));     
    } 
}

src/AppBundle/Resources/views/puntosinteres/articuloCompleto.html.twig
{% extends '::base.html.twig' %}
{% block title %} {{ puntoInteres.nombre }} {% endblock %}
{% block body %}

    
    <script>
    var myCenter=new google.maps.LatLng({{ puntoInteres.latitud }},{{ puntoInteres.longitud }});
    function initialize() {
      

      var mapProp = {
        center: myCenter,
        zoom:15,
        mapTypeId:google.maps.MapTypeId.ROADMAP
      };
      var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);
      var marker=new google.maps.Marker({
          position:myCenter,
          });
    
      marker.setMap(map);
    }
    google.maps.event.addDomListener(window, 'load', initialize);
    </script>
    
    <article class="articulo-punto-interes well">
        <div class="categoria" style="float: right;">    
            {% for cat in puntoInteres.categoria %}
                <div class="label label-success">{{ cat.nombre }}</div><br/>
            {% endfor %}
        </div>
        
        <div class="nombre">
            <h4>{{ puntoInteres.nombre }}</h4>
        </div>

        <div class="descripcion-puntos-interes">
            {{ puntoInteres.descripcion }}
        </div>
        <br/><br/>
    
        <div class="col-md-12">
            <div style="float: right">
                <div class="links-puntos-interes">
                    Localidad: {{ puntoInteres.localidad.nombre }}                    
                </div>
    
                <div class="direccion-interes">
                    Direccion: {{ puntoInteres.direccion }}
                </div>        
            </div>        
        </div>
    
        <div class="imagen-puntos-interes col-md-4">
            {% for foto in puntoInteres.fotos %}
                <img class="thumbnail" src="{{ foto.link }}" width="200"/>
            {% endfor %}
        </div>
    
        <div class="mapa-puntos-interes col-md-8">
            <div id="googleMap" style="height:380px;" class="thumbnail"></div>
        </div>
    
        <div class="links-puntos-interes">  
            <a href="http://{{ puntoInteres.linkinteres }}">{{ puntoInteres.linkinteres }}</a>                      
        </div>
    
        <div class="video-puntos-interes">
            {% for video in puntoInteres.videos %}
                <div class="label label-info">{{ video.link }}</div>
            {% endfor %}
        </div>
    
    </article>    
{% endblock %}

src/AppBundle/Resources/views/puntosinteres/articuloResumen.html.twig
<article class="well">
    
    <div class="media">
        <div class="media-left">
            {% if not puntoInteres.fotos.isEmpty %}
            <a href="#">
                <img class="media-object img-thumbnail" src="{{ puntoInteres.imagenPrincipalUrl }}" style="width: 150px">
            </a>
            {% endif %}
        </div>
        <div class="media-body">
            <h4 class="media-heading">{{ puntoInteres.nombre }}</h4>
            <p>{{puntoInteres.descripcion}}</p>
            <div class="categorias-puntos-interes">
                {% if is_granted('ROLE_SUPER_ADMIN') %}
                    <a href="{{ path('puntointeres_edit', { 'id': puntoInteres.id }) }}" class="btn btn-primary" style="float: right">
                        <span class="glyphicon glyphicon-pencil"></span> Editar
                    </a>
                    {% else %}
                    <a href="{{ path('puntosinteres_completo', { 'id': puntoInteres.id }) }}" class="btn btn-success" style="float: right">
                        <span class="glyphicon glyphicon-ok"> Ampliar</span>
                    </a>
                {% endif %}

                {% for cat in puntoInteres.categoria %}    
                    <div class="label label-info">{{ cat.nombre }}</div>
                {% endfor %}
            </div>
        </div>
    </div>
</article> 

src/AppBundle/Resources/views/puntosinteres/filtro.html.twig
{% extends '::base.html.twig' %}

{% block title %} Filtro puntos de interés {% endblock %}

{% block body %}

	<h3>Buscá los lugares más bonitos de Tierra del Fuego</h3>

	{{ form_start(form, {'attr':{'class':'content-fluid'}}) }}

	    {{ form_errors(form) }}
		
		<div class="form-group">
			<div class="col-md-10">
			    {{ form_widget(form.nombre, {
					'attr': {'class': 'form-control input-lg'}
		        	})
			     }}
			</div>

		    {{ form_widget(form.Filtrar, {
		    	'attr': {'style': 'display:none'}
		    	}) 
		    }}
		    <button type="submit" id="form_Filtrar" name="form[Filtrar]" class="col-md-2 btn btn-primary btn-lg"><span class="glyphicon glyphicon-search" ></span>  Buscar</button>
		        
		</div>
		<br/><br/>
{#        
        <style type="text/css">
	        .checkbox-form{float: left;}
    	</style>
        <div style="margin-top: 15px">
		    {%- for c in form.categoria %}
				<div class="col-md-3">
					{{ form_row(c, {
						'attr': {'class': 'checkbox-form'}
			        	}) 
					}}
				</div>
			{% endfor %}
        </div>
#}
	{{ form_end(form) }}

	<dir class="col-md-12">
		{% if puntosinteres is empty %}
			 
			  <div class="alert alert-warning text-center">
			  	<strong>No se encontraron resultados</strong>
			  </div>  

		{% else %}

			  <div class="alert alert-info text-center">
			  	Se encontraron <strong>{{ puntosinteres|length }}</strong> resultados 
			  </div>  

		    {% for p in puntosinteres %}
				{% include "AppBundle:puntosinteres:articuloResumen.html.twig" with {'puntoInteres': p} %}


{#		        <a href='{{ p.nombre|url_encode }}'>{{ p.nombre }} </a> <br/> #}
		    {% endfor %}

		{% endif %}
	</dir>
{% endblock %}

src/AppBundle/Resources/views/puntosinteres/index.html.twig
{% extends '::base.html.twig' %}

{% block title %} Puntos de interés {% endblock %}

{% block body %}
    
    <section class="row-fluid">
        <h1>Puntos de interés</h1>

        {% for puntointeres in puntosinteres %}
            <article class="articulo-punto-interes well">
                <div class="nombre">
                    <h4>{{ puntointeres.nombre }}</h4>
                </div>

                <div class="descripcion-puntos-interes">
                    {{ puntointeres.descripcion }}
                </div>

                <div class="mapa-puntos-interes">
                    {{ puntointeres.latitud }}
                    <br/>
                    {{ puntointeres.longitud }}
                </div>

                <div class="links-puntos-interes">
                    <a href="http://{{ puntointeres.linkinteres }}">{{ puntointeres.linkinteres }}</a>                    
                </div>

                <div class="direccion-interes">
                    {{ puntointeres.direccion }}
                </div>

                <div class="categorias-puntos-interes">
                    {% for cat in puntointeres.categorias %}
                        <div class="label label-success">{{ cat.nombre }}</div>
                    {% endfor %}
                </div>

                <div class="links-puntos-interes">
                    {{ puntointeres.localidad.nombre }}
                </div>

                <div class="imagen-puntos-interes">
                    {% for foto in puntointeres.fotos %}
                        <img src="{{ foto.link }}" width="200"/>
                    {% endfor %}
                </div>

                <div class="links-puntos-interes">
                    {% for video in puntointeres.videos %}
                        <div class="label label-info">{{ video.link }}</div>
                    {% endfor %}
                </div>

                <div class="links-puntos-interes">
                    {{ puntointeres.localidad.nombre }}                    
                </div>
            </article>
        {% endfor %}

    </section>
{% endblock %}